import { MockupConfig } from './types';
import {
  STUDIO_COMBO_FRAME,
  STUDIO_DESK_FRAME,
  STUDIO_LAPTOP_FRAME,
  STUDIO_MONITOR_FRAME,
  STUDIO_PHONE_ISLAND_FRAME,
  STUDIO_PHONE_NOTCH_FRAME,
  STUDIO_TABLET_FRAME,
  STUDIO_TABLET_THIN_FRAME,
  TRANSPARENT_PIXEL_GIF,
} from './lib/deviceFrames';

/**
 * Standard-Mockups orientieren sich an `MOCKUPS_EXAMPLE.html` (Laptop, Monitor,
 * Phone mit Notch / Dynamic Island, Tablet, dünnes Tablet, Schreibtisch-Combo,
 * Tablet+Phone) plus ein 3D-Laptop.
 */
export const DEFAULT_MOCKUPS: MockupConfig[] = [
  {
    id: 'studio-laptop',
    name: '01 — Laptop',
    imageUrl: STUDIO_LAPTOP_FRAME,
    builtinFrame: 'studioLaptop',
    corners: {
      tl: { x: 10.0, y: 10.0 },
      tr: { x: 90.0, y: 10.0 },
      br: { x: 90.0, y: 82.0 },
      bl: { x: 10.0, y: 82.0 },
    },
    deviceType: 'laptop',
    contentAspect: 1280 / 720,
    contentViewportWidth: 1280,
    isDefault: true,
  },
  {
    id: 'studio-monitor',
    name: '02 — Monitor',
    imageUrl: STUDIO_MONITOR_FRAME,
    builtinFrame: 'studioMonitor',
    corners: {
      tl: { x: 25.0, y: 10.2 },
      tr: { x: 75.0, y: 10.2 },
      br: { x: 75.0, y: 59.4 },
      bl: { x: 25.0, y: 59.4 },
    },
    deviceType: 'laptop',
    contentAspect: 800 / 492,
    contentViewportWidth: 1280,
    isDefault: true,
  },
  {
    id: 'studio-phone-notch',
    name: '03 — Phone · Notch',
    imageUrl: STUDIO_PHONE_NOTCH_FRAME,
    builtinFrame: 'studioPhoneNotch',
    corners: {
      tl: { x: 9.14, y: 4.57 },
      tr: { x: 90.86, y: 4.57 },
      br: { x: 90.86, y: 95.43 },
      bl: { x: 9.14, y: 95.43 },
    },
    deviceType: 'phone',
    contentAspect: 572 / 1272,
    contentViewportWidth: 390,
    isDefault: true,
  },
  {
    id: 'studio-phone-island',
    name: '04 — Phone · Dynamic Island',
    imageUrl: STUDIO_PHONE_ISLAND_FRAME,
    builtinFrame: 'studioPhoneIsland',
    corners: {
      tl: { x: 9.14, y: 4.57 },
      tr: { x: 90.86, y: 4.57 },
      br: { x: 90.86, y: 95.43 },
      bl: { x: 9.14, y: 95.43 },
    },
    deviceType: 'phone',
    contentAspect: 572 / 1272,
    contentViewportWidth: 390,
    isDefault: true,
  },
  {
    id: 'studio-tablet',
    name: '05 — Tablet',
    imageUrl: STUDIO_TABLET_FRAME,
    builtinFrame: 'studioTablet',
    corners: {
      tl: { x: 6.29, y: 8.8 },
      tr: { x: 94.57, y: 8.8 },
      br: { x: 94.57, y: 90.4 },
      bl: { x: 6.29, y: 90.4 },
    },
    deviceType: 'tablet',
    contentAspect: 1224 / 824,
    contentViewportWidth: 768,
    isDefault: true,
  },
  {
    id: 'studio-tablet-thin',
    name: '06 — Tablet · schmal',
    imageUrl: STUDIO_TABLET_THIN_FRAME,
    builtinFrame: 'studioTabletThin',
    corners: {
      tl: { x: 5.57, y: 7.8 },
      tr: { x: 94.43, y: 7.8 },
      br: { x: 94.43, y: 92.2 },
      bl: { x: 5.57, y: 92.2 },
    },
    deviceType: 'tablet',
    contentAspect: 1244 / 844,
    contentViewportWidth: 768,
    isDefault: true,
  },
  {
    id: 'studio-desk',
    name: '07 — Laptop & Phone · Desk',
    imageUrl: STUDIO_DESK_FRAME,
    builtinFrame: 'studioDeskLaptopPhone',
    corners: {
      tl: { x: 4.36, y: 5.6 },
      tr: { x: 48.0, y: 5.6 },
      br: { x: 48.0, y: 65.6 },
      bl: { x: 4.36, y: 65.6 },
    },
    deviceType: 'laptop',
    contentAspect: 960 / 600,
    contentViewportWidth: 1280,
    isDefault: true,
  },
  {
    id: 'studio-tablet-phone',
    name: '08 — Tablet & Phone',
    imageUrl: STUDIO_COMBO_FRAME,
    builtinFrame: 'studioTabletPhoneCombo',
    corners: {
      tl: { x: 3.09, y: 14.8 },
      tr: { x: 56.91, y: 14.8 },
      br: { x: 56.91, y: 85.2 },
      bl: { x: 3.09, y: 85.2 },
    },
    deviceType: 'tablet',
    contentAspect: 1184 / 704,
    contentViewportWidth: 768,
    isDefault: true,
  },
  {
    id: 'print-business-card',
    name: 'Druck · Visitenkarte (ISO)',
    imageUrl: TRANSPARENT_PIXEL_GIF,
    builtinFrame: 'printBusinessCard',
    corners: {
      tl: { x: 7.5, y: 14.29 },
      tr: { x: 92.5, y: 14.29 },
      br: { x: 92.5, y: 85.71 },
      bl: { x: 7.5, y: 85.71 },
    },
    deviceType: 'print',
    contentAspect: 1360 / 720,
    contentViewportWidth: 900,
    isDefault: true,
  },
  {
    id: 'print-poster-a2',
    name: 'Druck · Plakat (A2 Hochformat)',
    imageUrl: TRANSPARENT_PIXEL_GIF,
    builtinFrame: 'printPoster',
    corners: {
      tl: { x: 12.86, y: 13.0 },
      tr: { x: 84.29, y: 13.0 },
      br: { x: 84.29, y: 83.2 },
      bl: { x: 12.86, y: 83.2 },
    },
    deviceType: 'print',
    contentAspect: 1000 / 1414,
    contentViewportWidth: 1200,
    isDefault: true,
  },
  {
    id: 'print-flyer-a5',
    name: 'Druck · Flyer (A5 Hochformat)',
    imageUrl: TRANSPARENT_PIXEL_GIF,
    builtinFrame: 'printFlyer',
    corners: {
      tl: { x: 11.67, y: 12.94 },
      tr: { x: 88.33, y: 12.94 },
      br: { x: 88.33, y: 89.65 },
      bl: { x: 11.67, y: 89.65 },
    },
    deviceType: 'print',
    contentAspect: 920 / 1304,
    contentViewportWidth: 900,
    isDefault: true,
  },
  {
    id: 'print-generic',
    name: 'Druck · Sonstiges (Quadrat)',
    imageUrl: TRANSPARENT_PIXEL_GIF,
    builtinFrame: 'printGeneric',
    corners: {
      tl: { x: 12.5, y: 12.5 },
      tr: { x: 87.5, y: 12.5 },
      br: { x: 87.5, y: 87.5 },
      bl: { x: 12.5, y: 87.5 },
    },
    deviceType: 'print',
    contentAspect: 1,
    contentViewportWidth: 1200,
    isDefault: true,
  },
  {
    id: 'default-3d-laptop',
    name: '3D Laptop',
    imageUrl: TRANSPARENT_PIXEL_GIF,
    renderMode: 'three',
    deviceType: 'laptop',
    corners: {
      tl: { x: 10.0, y: 10.0 },
      tr: { x: 90.0, y: 10.0 },
      br: { x: 90.0, y: 82.0 },
      bl: { x: 10.0, y: 82.0 },
    },
    contentAspect: 1280 / 720,
    contentViewportWidth: 1280,
    isDefault: true,
  },
];

export const STORAGE_KEY = 'live-mockup-studio-custom-configs-v2';
export const LEGACY_STORAGE_KEY = 'live-mockup-studio-custom-configs';
